/**
 * Brand diagnostic report files (V2 9-chapter reports generated by the GEO
 * pipeline on the server, not the elmo native report system).
 *
 * Report artifacts live in a server-side output dir (default
 * /srv/geo/brand_report/data/v2_reports) as GEO-Diagnostic-<code>-<yyyymmdd>-zh.{pdf,json}.
 * The PDF is also copied to the web public dir as report-<brandId>.pdf by the
 * pipeline for direct download.
 */
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import fs from "node:fs";
import path from "node:path";
import { requireAuthSession, requireOrgAccess } from "@/lib/auth/helpers";

export const REPORTS_DIR =
	process.env.GEO_REPORTS_DIR || "/srv/geo/brand_report/data/v2_reports";
export const WEB_PUBLIC_DIR =
	process.env.GEO_WEB_PUBLIC_DIR || "/srv/geo/elmo-src/apps/web/public";

export interface BrandReportSummary {
	file: string; // stem, e.g. GEO-Diagnostic-dji-20260828-zh
	clientCode: string;
	generatedAt: string; // ISO mtime
	pdfInOutput: boolean;
	pdfUrl: string | null; // public URL if a public copy exists
	meta: {
		brandName?: string;
		totalSamples?: number;
		startDate?: string;
		endDate?: string;
	};
	gatesPassed: number; // 0-8
	gatesTotal: number;
}

function parseReportJson(filePath: string) {
	try {
		const raw = JSON.parse(fs.readFileSync(filePath, "utf-8")) as {
			meta?: { brand_name?: string; total_samples?: number; start_date?: string; end_date?: string };
			gates?: unknown;
			q7?: Array<{ passed?: boolean }>;
			q8_mismatches?: unknown[];
		};
		const q7 = Array.isArray(raw.q7) ? raw.q7 : [];
		const gatesPassed =
			q7.length > 0
				? q7.filter((g) => g.passed === true).length
				: Array.isArray(raw.gates)
					? (raw.gates as Array<{ passed?: boolean }>).filter((g) => g.passed === true).length
					: 0;
		return {
			meta: raw.meta || {},
			gatesPassed,
			gatesTotal: q7.length > 0 ? q7.length : 8,
		};
	} catch {
		return { meta: {}, gatesPassed: 0, gatesTotal: 0 };
	}
}

export const getBrandReports = createServerFn({ method: "GET" })
	.validator(z.object({ brandId: z.string() }))
	.handler(async ({ data }) => {
		const session = await requireAuthSession();
		await requireOrgAccess(session.user.id, data.brandId);

		if (!fs.existsSync(REPORTS_DIR)) {
			return [];
		}

		const want = data.brandId.toLowerCase();
		const files = fs.readdirSync(REPORTS_DIR).filter((f) => f.endsWith(".json"));
		const reports: BrandReportSummary[] = [];

		for (const f of files) {
			const m = f.match(/^GEO-Diagnostic-(.+)-(\d{8})-zh\.json$/);
			if (!m) continue;
			const code = m[1];
			if (code.toLowerCase() !== want) continue;
			const stem = f.replace(/\.json$/, "");
			const pdfInOutput = fs.existsSync(path.join(REPORTS_DIR, `${stem}.pdf`));
			const stat = fs.statSync(path.join(REPORTS_DIR, f));
			const parsed = parseReportJson(path.join(REPORTS_DIR, f));
			// public copy is normalized to report-<brandId>.pdf (lowercase id)
			const publicPdf = path.join(WEB_PUBLIC_DIR, `report-${data.brandId.toLowerCase()}.pdf`);
			const pdfUrl =
				fs.existsSync(publicPdf) || fs.existsSync(path.join(WEB_PUBLIC_DIR, `report-${code}.pdf`))
					? `/report-${data.brandId.toLowerCase()}.pdf`
					: null;
			reports.push({
				file: stem,
				clientCode: code,
				generatedAt: stat.mtime.toISOString(),
				pdfInOutput,
				pdfUrl,
				meta: {
					brandName: parsed.meta.brand_name,
					totalSamples: parsed.meta.total_samples,
					startDate: parsed.meta.start_date,
					endDate: parsed.meta.end_date,
				},
				gatesPassed: parsed.gatesPassed,
				gatesTotal: parsed.gatesTotal,
			});
		}

		return reports.sort((a, b) => (a.generatedAt < b.generatedAt ? 1 : -1));
	});
